# Generated by Django 3.2.6 on 2022-11-14 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def link_authors(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    User = apps.get_model("account", "User")
    for article in Article.objects.all():
        author = User.objects.get_or_create(username=article.author)[0]
        article.author_link = author
        article.save()


def link_categories(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    Category = apps.get_model("blog", "Category")
    for article in Article.objects.all():
        category = Category.objects.get_or_create(title=article.category)[0]
        article.category_link = category
        article.save()


def fill_updated(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    for article in Article.objects.all():
        article.updated = article.created
        article.save()


def fill_published(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    for article in Article.objects.all():
        article.published = article.created
        article.save()


def fill_status(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    for article in Article.objects.all():
        article.status = "p"
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="author_link",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to="account.User"),
        ),
        migrations.RunPython(
            code=link_authors
        ),
        migrations.RemoveField(
            model_name="article",
            name="author"
        ),
        migrations.RenameField(
            model_name="article",
            old_name="author_link",
            new_name="author"
        ),
        migrations.AddField(
            model_name="article",
            name="category_link",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="blog.category"),
        ),
        migrations.RunPython(
            code=link_categories
        ),
        migrations.RemoveField(
            model_name="article",
            name="category"
        ),
        migrations.RenameField(
            model_name="article",
            old_name="category_link",
            new_name="category"
        ),
        migrations.AddField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            code=fill_updated
        ),
        migrations.AddField(
            model_name="article",
            name="published",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(
            code=fill_published
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(max_length=1, null=False, default="d"),
        ),
        migrations.RunPython(
            code=fill_status
        ),
    ]
