# Generated by Django 3.2.6 on 2022-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_create_category_and_complete_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
